version: '3.9'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-react
    container_name: test-react
    stdin_open: true
    ports:
      - 5173:5173
    volumes:
      - .:/app
