name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-18
    steps:
      - name: Echo message
        run: |
          echo "Hello, world!"
      - run: ll